'use strict';var Ff=function(a){this.iE="number"==typeof a?0<a?1:0>a?-1:null:null==a?null:a?-1:1};Ff.prototype.CU=function(a,b){var c=0,e=0,f=!1;a=Pb(a,b).split(Tb);for(b=0;b<a.length;b++){var g=a[b];Rb.test(Pb(g,void 0))?(c++,e++):Sb.test(g)?f=!0:Qb.test(Pb(g,void 0))?e++:Ub.test(g)&&(f=!0)}return 0==e?f?1:0:.4<c/e?-1:1};Ff.prototype.YT=function(a,b){return this.f1(this.CU(a,b))};Ff.prototype.f1=function(a){return-1==(0==a?this.iE:a)?"rtl":"ltr"};
Ff.prototype.mark=function(){switch(this.iE){case 1:return"\u200e";case -1:return"\u200f";default:return""}};if("undefined"!=typeof angular){var Gf=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&Gf.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){var b=this;this.Kv=this.ne=null;a.dirForText=function(a){b.ne||(b.ne=chrome.i18n.getMessage("@@bidi_dir")||"ltr");b.Kv||(b.Kv=new Ff("rtl"==b.ne));return b.Kv.YT(a||"")}}],compile:function(a,b){b=b.key;var c=null,e=document.createElement("amr");
b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&e.setAttribute("id","missing"));if(b){var f=chrome.i18n.getMessage(b+"_ph"),c=[];if(null!=f)for(c=f.split("\ue000"),f=0;f<c.length;++f)c[f]=c[f].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else e.setAttribute("r","nokey");c?e.innerHTML=c:(e.setAttribute("tl","false"),e.innerHTML=a.html());a.replaceWith(e)}}})};var Hf=/^[\w+/]+[=]{0,2}$/;var If=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var e=c||h,f=e.document,g;g=(g=(g=(e||h).document.querySelector("script[nonce]"))&&g.getAttribute("nonce"))&&Hf.test(g)?g:void 0;g&&(a.nonce=g);if("help"==a.flow){var k=oa("document.location.href",e);!a.helpCenterContext&&k&&(a.helpCenterContext=k.substring(0,1200));k=!0;if(b&&JSON&&JSON.stringify){var p=JSON.stringify(b);(k=1200>=p.length)&&(a.psdJson=p)}k||(b={invalidPsd:!0})}b=[a,b,c];e.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||
"//www.google.com/tools/feedback";if(k=e.GOOGLE_FEEDBACK_START)k.apply(e,b);else{var e=c+"/load.js?",q;for(q in a)b=a[q],null!=b&&!xa(b)&&(e+=encodeURIComponent(q)+"="+encodeURIComponent(b)+"&");a=f.createElement("script");g&&a.setAttribute("nonce",g);a.src=e;f.body.appendChild(a)}};m("userfeedback.api.startFeedback",If,void 0);var Jf=function(a,b,c,e,f,g){this.userEmail=a;this.cJ=b;this.RU=c;this.a2=e;this.modelName=f;this.receiverVersion=g};var Kf=chrome.i18n.getMessage("4163185390680253103"),Lf=chrome.i18n.getMessage("492097680647953484"),Mf=chrome.i18n.getMessage("2575016469622936324"),Nf=chrome.i18n.getMessage("128276876460319075"),Of=chrome.i18n.getMessage("3326722026796849289"),Pf=chrome.i18n.getMessage("1018984561488520517"),Qf=chrome.i18n.getMessage("8205999658352447129"),Rf=chrome.i18n.getMessage("5723583529370342957"),Sf=chrome.i18n.getMessage("1550904064710828958"),Tf=chrome.i18n.getMessage("5014364904504073524"),Uf=chrome.i18n.getMessage("2194670894476780934"),
Vf=chrome.i18n.getMessage("6614468912728530636"),Wf=chrome.i18n.getMessage("5910595154486533449"),Xf=chrome.i18n.getMessage("5363086287710390513"),Yf=chrome.i18n.getMessage("244647017322945605"),Zf=chrome.i18n.getMessage("5375576275991472719"),$f=chrome.i18n.getMessage("4592127349908255218"),ag=chrome.i18n.getMessage("843316808366399491"),bg=chrome.i18n.getMessage("5699813974548050528"),cg=chrome.i18n.getMessage("8515148417333877999"),dg=chrome.i18n.getMessage("1636686747687494376"),eg=chrome.i18n.getMessage("4148300086676792937"),
fg=chrome.i18n.getMessage("3219866268410307919"),gg=chrome.i18n.getMessage("9211708838274008657"),hg=chrome.i18n.getMessage("8706273405040403641"),ig=chrome.i18n.getMessage("4756056595565370923"),jg=chrome.i18n.getMessage("7876724262035435114"),kg=chrome.i18n.getMessage("5485620192329479690"),lg=chrome.i18n.getMessage("6963873398546068901"),mg=chrome.i18n.getMessage("3567591856726172993"),og=chrome.i18n.getMessage("3239956785410157548");var pg=function(a,b){var c=this;this.CE=b;this.l=a;this.l.top=a;this.dF=[];this.iC=!1;this.xba();this.qba();this.rba();this.sba();this.uba();this.TU=Sa();this.l.userEmail="";chrome.identity.getProfileUserInfo(function(a){c.l.userEmail=a.email;c.rp()});this.l.yourAnswerText=og;this.l.language=chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.l.requestLogsInProgress=!1};d=pg.prototype;
d.qba=function(){this.dF=[{value:"Bug",desc:Kf},{value:"FeatureRequest",desc:Lf},{value:"MirroringQuality",desc:Mf},{value:"Discovery",desc:Nf},{value:"Other",desc:Of}];this.l.feedbackTypes=this.dF};d.KB=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new qg(c,arguments[c]));b.push(new qg(0,arguments[0]));return b};
d.xba=function(){this.l.videoSmoothnessRatings=this.KB(Uf,Pf,Qf,Rf,Sf,Tf);this.l.videoQualityRatings=this.KB(Uf,Vf,Wf,Xf,Yf,Zf);this.l.audioQualityRatings=this.KB(Uf,$f,ag,bg,cg,dg)};d.rba=function(){this.l.includeFineLogs=!0;this.l.feedbackType="Bug";this.l.sendFeedback=u(this.T7,this);this.l.cancel=u(this.yS,this);this.l.attachLogsClick=u(this.iD,this);this.l.viewLogs=u(this.zda,this)};
d.sba=function(){this.l.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),u(this.QS,this));this.l.sufficientFeedback=!1};d.uba=function(){this.l.$watch("attachLogs",u(this.iD,this));this.l.attachLogs=!0};d.yS=function(){this.l.feedbackDescription&&!confirm(eg)||window.close()};
d.QS=function(){var a=this.l.feedbackType;this.l.sufficientFeedback="MirroringQuality"==a?this.l.videoSmoothness||this.l.videoQuality||this.l.audioQuality||this.l.comments:"Discovery"==a?this.l.visibleInSetup||this.l.comments:!!this.l.feedbackDescription};
d.T7=function(){if(this.l.sufficientFeedback){var a=this.l.feedbackType,b="";"MirroringQuality"==a?(this.l.videoSmoothness&&(b+="\nVideo Smoothness: "+this.l.videoSmoothness),this.l.videoQuality&&(b+="\nVideo Quality: "+this.l.videoQuality),this.l.audioQuality&&(b+="\nAudio: "+this.l.audioQuality),this.l.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.l.projectedContentUrl),this.l.comments&&(b+="\nComments: "+this.l.comments)):"Discovery"==a?(this.l.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.l.visibleInSetup),this.l.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.l.hasNetworkSoftware),this.l.networkDescription&&(b+="\nNetwork Description: "+this.l.networkDescription),this.l.comments&&(b+="\nComments: "+this.l.comments)):b=this.l.feedbackDescription;this.S7("Type: "+a+"\n\n"+b)}};
d.S7=function(a){this.l.sendDialogText=fg;this.l.okButton=mg;this.l.feedbackSent=!1;this.CE.show({locals:{Lla:this.l.feedbackSent,Ara:this.l.sendDialogText,l2:this.l.okButton},scope:this.l,preserveScope:!0,bindToController:!0,template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.ev});this.RL(a,v())};d.RL=function(a,b){var c=v();!this.l.requestLogsInProgress||5E3<c-b?this.jU(a):setTimeout(u(this.RL,this),1E3,a,b)};
d.jU=function(a){var b=this,c=0,e=function(a,c,e){e?a(!0):(b.l.sendDialogText=ig,b.rp(),c(Error("Failed to send")))},f=chrome.declarativeWebRequest?"MrTeamfood":"MRStable";(new jf(function(){c++;return new Promise(function(c,k){var g=new Jf(b.l.userEmail||"",b.l.logs||"",b.l.externalLogs||"",b.l.mirrorLogUrl||"",b.l.modelName||"",b.l.receiverVersion||"");c=Ca(e,c,k);k=chrome.runtime.getManifest();If({productId:85561,bucket:f,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,
locale:k.default_locale,enableAnonymousFeedback:!g.userEmail,report:{description:a},callback:c},{version:k.version,description:k.description,user_email:g.userEmail||"NA",logs:g.cJ||"NA",external_logs:g.RU||"NA",device_model:g.modelName||"NA",receiver_version:g.receiverVersion||"NA",dash_report_url:g.a2||"NA"})})},1E4,4)).Xt(2).start().then(function(){b.l.sendDialogText=hg;b.l.feedbackSent=!0;b.rp()},function(){b.l.sendDialogText=gg;b.l.feedbackSent=!0;b.rp()})};
d.iD=function(){var a=this;this.l.logs="";this.l.externalLogs=null;this.l.mirrorLogUrl="";this.l.modelName="";this.l.receiverVersion="";this.l.attachLogs&&(this.l.requestLogsInProgress=!0,chrome.runtime.sendMessage(new Ef(this.TU,"retrieve_log_data"),function(b){a.l.requestLogsInProgress=!1;a.l.logs=b.logs||"no extension";a.l.mirrorLogUrl=b.castStreamingLogs||"";if((b=b.device)&&b.model&&(a.l.modelName=b.model,a.l.receiverVersion=b.version||"",!a.iC)){var c=Sa();a.iC=!0;a.l.externalLogs=Bf(b.ip,c,
u(a.H3,a))}}))};
d.zda=function(){this.l.logsHeader=jg;this.l.sendLogs=kg;this.l.fineLogsWarning=lg;this.l.okButton=mg;this.CE.show({locals:{zia:this.l.attachLogs,cJ:this.l.logs,ana:this.l.includeFineLogs,Una:this.l.logsHeader,Bra:this.l.sendLogs,Nla:this.l.fineLogsWarning,l2:this.l.okButton},scope:this.l,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.ev})};
d.H3=function(a,b){this.iC=!1;this.l.externalLogs="error"==a?null:b;this.l.attachLogs||(this.l.externalLogs=null);this.rp()};d.rp=function(){this.l.$$phase||this.l.$apply()};d.ev=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};pg.prototype.ev.$inject=["$scope","$mdDialog"];var qg=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};
angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",pg]);m("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.vl?!0:!1},void 0);m("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0},void 0);m("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof ic)return jc(a);if(a instanceof mc)return nc(a);if(a instanceof fc)return gc(a);if(a instanceof cc)return dc(a);if(a instanceof pc)return qc(a);throw Error();},void 0);
m("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return nc(b);if("resourceUrl"==a||"templateUrl"==a)return jc(b);if("url"==a)return b instanceof ic?jc(b):gc(b);if("css"==a)return dc(b);if("js"==a)return qc(b);throw Error();},void 0);
