'use strict';var rg;m("mr.IssueSeverity",{cfa:"fatal",Xha:"warning",kga:"notification"},void 0);m("mr.IssueAction",{Sea:"dismiss",Tfa:"learn_more"},void 0);var sg=function(a,b,c){this.routeId=null;this.severity=b;this.isBlocking="fatal"==this.severity?!0:!1;this.title=a;this.message=null;this.defaultAction=c;this.helpPageId=this.secondaryActions=null};sg.prototype.M9=function(a){this.helpPageId=a;return this};sg.prototype.Baa=function(a){this.secondaryActions=a;return this};
sg.prototype.S9=function(a){if(!a&&"fatal"==this.severity)throw Error("All FATAL issues must be blocking.");this.isBlocking=a;return this};var tg=function(a,b){var c=this;this.No=void 0===b?null:b;this.promise=new Promise(function(b,f){var e=function(a){c.No=null;f(a)};c.gp=e;a(function(a){c.No=null;b(a)},e)})};tg.prototype.cancel=function(a){this.gp(a);if(this.No){var b=this.No;this.No=null;setTimeout(function(){return b(a)},0)}};
tg.prototype.bw=function(a,b){b=void 0===b?null:b;var c=this;return new tg(function(e,f){c.promise.then(function(b){if(a)try{e(a(b))}catch(k){f(k)}else e(b)},function(a){if(b)try{e(b(a))}catch(k){f(k)}else f(a)})},function(a){c.cancel(a)})};tg.prototype.then=function(a,b){return this.bw(a,void 0===b?null:b)};tg.prototype.catch=function(a){return this.bw(null,a)};
var ug=function(a){return new tg(function(b){b(a)})},vg=function(a){return new tg(function(b,c){c(a)})},wg=function(a){return new tg(function(b,c){a.then(b,c)})},xg=function(a,b){var c=!1,e=null;return new tg(function(f,g){a.then(function(a){c||(e=b(a),e.promise.then(f,g))},g)},function(a){e?e.cancel(a):c=!0})};var yg=function(a){this.Nb=a;this.Cm=v()};yg.prototype.sx=function(a,b){null!=b&&(a+="_"+b);return a};yg.prototype.qm=function(a){this.Nb=a};yg.prototype.end=function(a){var b=v()-this.Cm;zg(this.sx(this.Nb,a),b)};var zg=function(a,b){0>b&&(F(Ag,"Timing analytics event with negative time"),b=0);1E4<b&&(b=1E4);try{chrome.metricsPrivate.recordTime(a,b)}catch(c){F(Ag,"Failed to record time "+b+" in "+a)}},Ag=D("mr.Timing"),Bg=function(a){yg.call(this,a)};ja(Bg,yg);
Bg.prototype.end=function(a){var b=v()-this.Cm;a=this.sx(this.Nb,a);if(0>b)F(Cg,"Timing analytics event with negative time");else{1E4>b&&(b=1E4);18E4<b&&(b=18E4);try{chrome.metricsPrivate.recordMediumTime(a,b)}catch(c){F(Cg,"Failed to record time "+b+" in "+a)}}};var Cg=D("mr.MediumTiming"),Dg=function(a){yg.call(this,a)};ja(Dg,yg);
Dg.prototype.end=function(a){var b=v()-this.Cm;a=this.sx(this.Nb,a);if(0>b)F(Eg,"Timing analytics event with negative time");else{18E4>b&&(b=18E4);36E5<b&&(b=36E5);try{chrome.metricsPrivate.recordLongTime(a,b)}catch(c){F(Eg,"Failed to record time "+b+" in "+a)}}};
var Eg=D("mr.LongTiming"),Fg=D("mr.Analytics"),Gg=function(a){try{chrome.metricsPrivate.recordUserAction(a)}catch(b){F(Fg,"Failed to record event "+a)}},Hg=function(a,b,c){var e,f=0,g;for(g in c)f++,c[g]==b&&(e=g);if(l(e)){c={metricName:a,type:"histogram-linear",min:1,max:f,buckets:f+1};try{chrome.metricsPrivate.recordValue(c,b)}catch(k){F(Fg,"Failed to record enum value "+e+" ("+b+") in "+a,k)}}else E(Fg,"Unknown analytics value, "+b+" for histogram, "+a,Error())};var Ig={yea:0,wea:1,Aea:2,xea:3,eea:4,zea:5,xfa:6,Aha:7,Oea:8,EC:9},Jg=function(a,b){this.reason=0<=b&&9>=b?b:9};ja(Jg,Error);var Kg=function(){return null!=Vb&&-1!=Vb.indexOf("CrOS")},Lg=function(){var a=Vb;if(!r(a))return!1;a=a.match(/Windows NT \d+.\d+/);if(null===a||!ua(a))return!1;a=a[0];a=a.match(/\d+.\d+/);if(null===a||!ua(a))return!1;a=a[0];return 6.2<=parseFloat(a)},Mg=function(){return Kg()?"ChromeOS":ad?"Windows":$c?"Mac":bd?"Linux":"Other"};var Ng=function(a){this.pi=a;this.sc=this.Vl=null;this.a=D("mr.mirror.MirrorMediaStream")};d=Ng.prototype;d.fN=function(a){this.Vl=a};d.gx=function(){return this.pi};d.start=function(){return this.pi.zI()?this.fca():this.pi.wI()?this.Zba():this.Vba()};
d.fca=function(){var a=this,b=this.pi.JB();G(this.a,"Starting tab capture with constraints "+JSON.stringify(b));return new Promise(function(c,e){chrome.tabCapture.capture(b,function(b){b?(a.hB(b),c(a)):e(a.uE())});window.setTimeout(function(){e(new Jg("chrome.tabCapture.capture failed to call its callback",2))},5E3)})};d.d0=function(a){a&&G(this.a,"Track "+JSON.stringify(a.target)+" ended");this.stop()};
d.uE=function(){return chrome.runtime.lastError&&chrome.runtime.lastError.message?new Jg(chrome.runtime.lastError.message,7):new Jg("empty_stream",0)};
d.Vba=function(){var a=this;return(new Promise(function(a,c){var b=["screen","audio"];"Linux"==Mg()&&b.push("window");var f=chrome.desktopCapture.chooseDesktopMedia(b,a);window.setTimeout(function(){chrome.desktopCapture.cancelChooseDesktopMedia(f);c(new Jg("timeout",1))},6E4)})).then(function(b){var c=a.pi.JB(b);G(a.a,"Starting desktop capture with constraints "+JSON.stringify(c));return new Promise(function(a){navigator.webkitGetUserMedia(c,a,function(a){throw new Jg(a.name+" "+a.constraintName+
": "+a.message,8);})})}).then(function(b){if(b)a.hB(b);else throw new Jg("empty_stream",8);return a})};d.Zba=function(){var a=this,b=this.pi.JB();G(this.a,"Starting offscreen tab capture with constraints "+JSON.stringify(b));return new Promise(function(c,e){chrome.tabCapture.captureOffscreenTab(a.pi.k2.toString(),b,function(b){b?(a.hB(b),c(a)):e(a.uE())})})};d.hB=function(a){var b=this;this.sc=a;a.getTracks().forEach(function(a){a.onended=b.d0.bind(b)})};
d.stop=function(){this.sc&&(this.sc.getTracks().forEach(function(a){a.onended=null;a.stop()}),this.sc=null,this.Vl&&this.Vl())};var Pg=function(a){return Og(a)||"urn:x-org.chromium.media:source:desktop"==a},Qg=function(a){if(!Ea(a,"http:")&&!Ea(a,"https:"))return!1;var b=document.createElement("a");b.href=a;return"http:"!=b.protocol&&"https:"!=b.protocol?!1:-1==b.hash.indexOf("__castAppId__")},Rg=["https://docs.google.com"],Og=function(a){return Ea(a,"urn:x-org.chromium.media:source:tab:")||-1!=a.indexOf("0F5096E8")};var Sg=function(a){return(new Promise(function(b){chrome.tabs.get(a,b)})).then(function(b){if(!b)throw Error("No such tab "+a);return b})};var Tg=chrome.i18n.getMessage("1639753794700094338");var Ug=function(a,b){I.call(this);this.h8=a;this.kj=b;this.Ze=this.Ja=null;this.m=D("mr.mirror.Service."+a);this.vz=u(this.b0,this);this.ln=!1};ja(Ug,I);d=Ug.prototype;d.getName=function(){return this.h8};
d.Np=function(a,b,c,e,f){var g=this;G(this.m,"Start mirroring on route "+a.id);var k=this.eg(b,c,e);return wg(this.TE(b,a.ze.tabId).then(function(){return g.bO()}).then(function(){return(new Ng(k.gx())).start()}).then(function(b){g.Ze=b;b.fN(function(){g.Vl(b)});return f?f(a).promise:a}).then(function(a){g.Ja=g.fr(k,a);return g.Ja.start(g.Ze.sc)}).then(function(){k.ry()&&!chrome.tabs.onUpdated.hasListener(g.vz)&&chrome.tabs.onUpdated.addListener(g.vz);return g.GK(a,k,c)}).then(null,function(a){g.nK(a);
g.Rf();throw a;}))};d.Ou=function(a,b,c,e,f,g){G(this.m,"Update mirroring on route "+a.id);return wg(this.TE(b,f).then(this.kU.bind(this,a,b,c,e,g)))};d.TE=function(a,b){return Og(a)?b?Sg(b).then(function(a){if(!a.active)throw new Jg("Tab to be mirrored is not active",7);}):Promise.reject(new Jg("BUG: Tab ID is required.")):Promise.resolve()};
d.kU=function(a,b,c,e,f){var g=this;b=this.eg(b,c,e);if(!this.Ja.jO())return Promise.reject(new Jg("Session does not support updating stream",7));var k=!1;return(new Ng(b.gx())).start().then(function(b){var c=g.Ze;g.Ze=b;b.fN(u(g.Vl,g,b));k=!0;c.stop();return f?f(a).promise:a}).then(function(a){g.Ja.xaa(a);return g.Ja.PO(g.Ze.sc)}).then(this.GK.bind(this,a,b,c)).then(null,function(a){g.nK(a);k&&g.Rf();throw a;})};
d.GK=function(a,b,c){var e=this;return new Promise(function(f,g){if(b.ry())e.Ja.oda(a.ze.tabId).then(function(){e.Ja.Rt();e.Et();f(e.Ja.Ya)},function(a){E(e.m,"Failed to obtain initial tab info.",a);g(a)});else{if(b.xI()){var k="Capturing "+a.mediaSource;e.Ja.aB(k,k,null);e.Ja.Rt();e.dA()}else e.Ja.aB("Capturing Desktop","Capturing Desktop",null),e.Ja.Rt(),e.At();e.MS(c,e.Ze);f(e.Ja.Ya)}})};
d.nK=function(a){a.reason=null!=a.reason?a.reason:9;E(this.m,"Failed to start mirroring: "+a.message+",  reason = "+a.reason+": "+a.stack);this.Ct(a.reason)};d.Vl=function(a){this.Ze==a&&(this.Dt(),this.Rf())};d.bO=function(){var a=this;return this.Rf().then(function(b){b&&a.Bt();return b})};
d.Rf=function(){var a=this;if(this.ln)return Promise.resolve(!1);this.ln=!0;chrome.tabs.onUpdated.removeListener(this.vz);this.Ze&&(this.Ze.stop(),this.Ze=null);if(this.Ja)return this.rD().then(function(){a.Ja&&(a.Ja.stop(),a.Ja.pb(),a.kj.nz(a.Ja.Ya.id),a.Ja=null);a.ln=!1;return!0},function(b){E(a.m,"Error cleaning up",b);a.ln=!1});this.ln=!1;return Promise.resolve(!1)};d.rD=function(){return Promise.resolve()};
d.b0=function(a,b,c){this.Ja&&this.Ja.tabId&&this.Ja.tabId==a&&("complete"==b.status||b.favIconUrl&&"complete"==c.status)&&(this.Ja.QO(c),this.kj.$J(this.Ja.Ya),this.Ja.Rt())};d.MS=function(a,b){a.captureAudio&&b.sc&&!b.sc.getAudioTracks().length&&this.kj.dg().send(new sg(Tg,"notification","dismiss"))};d.eg=function(){};d.fr=function(){};d.Et=function(){};d.At=function(){};d.dA=function(){};d.Bt=function(){};d.Ct=function(){};d.Dt=function(){};var Vg=function(a){I.call(this);this.Ya=a;this.ys=!1;this.tabId=this.jA=this.iconUrl=null};ja(Vg,I);d=Vg.prototype;d.aB=function(a,b,c){this.Ya.description=a;this.ys||this.Ya.offTheRecord?this.iconUrl=this.jA=null:(this.jA=b,this.iconUrl=c)};d.Rt=function(){this.ys||this.Ya.offTheRecord||this.VL()};d.oda=function(a){this.tabId=a;return Sg(a).then(this.QO.bind(this))};
d.QO=function(a){this.ys=a.incognito;this.aB(a.title,Ea(a.url,"file://")?"Local content (Tab)":Sd(a.url.match(Rd)[3]||null,!0)+" (Tab)",a.favIconUrl)};d.xaa=function(a){this.Ya=a};d.eg=function(){};d.start=function(){};d.jO=function(){return!1};d.PO=function(){};d.stop=function(){};d.L=function(){this.stop()};d.VL=pa;var Wg=function(a,b){this.type=a;this.data=b},Xg=function(a){a=JSON.parse(a);if(!a.type)throw Error("Invalid message");return new Wg(a.type,a.data)},Yg=function(a,b,c,e){this.description=a;this.settings=b||null;this.mediaConstraints=c||null;this.presentationUrl=e||null};var Zg={CC:0,rC:1,$P:2},$g=function(a){Hg("MediaRouter.WebRtc.Start.Success",a,Zg)};var bh=function(a,b){I.call(this);this.a=Nd("cv2.PeerConnection");this.P1=ah;this.o=this.yT(b);this.zw=this.tT(a);this.uU=!0;this.aM=new Vd;this.GA=!1;this.dt=0;this.ss=null;this.II=this.gz=0;this.Fb=!1;this.RJ=this.SJ=this.jz=this.aK=this.E2=pa};ja(bh,I);d=bh.prototype;d.cN=function(a){this.jz=a};d.bN=function(a){this.SJ=a};d.aN=function(a){this.RJ=a};d.eN=function(a){this.aK=a};d.dN=function(a){this.zw.onmessage=function(b){a(b.data)}};d.Bs=function(){return this.Fb};
d.BY=function(a){var b={};b.iceServers=[{url:"stun:stun.l.google.com:19302"}].concat(a);return b};d.yT=function(a){a=this.BY(a);var b=new webkitRTCPeerConnection(a);b.onicecandidate=u(this.lz,this);b.Gpa=u(this.Z2,this);b.oniceconnectionstatechange=u(this.Y2,this);G(this.a,"Created webkitRTCPeerConnnection with config: "+JSON.stringify(a));return b};d.tT=function(a){return this.o.createDataChannel(a,{reliable:!1})};d.Q7=function(a){"string"==typeof a?this.zw.send(a):this.zw.send(JSON.stringify(a))};
d.start=function(){this.Fb||(this.Fb=!0,this.sn())};d.stop=function(){G(this.a,"Stopping peer connection...");this.Fb&&(this.Fb=!1,"closed"!=this.o.signalingState&&this.o.close())};d.addStream=function(a){this.o.addStream(a)};d.removeStream=function(a){this.Fb&&this.o.removeStream(a)};d.L=function(){this.stop();this.o=null};
d.sn=function(){var a=this;G(this.a,"Sending offer to peer.");this.gz=v();this.o.createOffer(u(this.MM,this),function(b){F(a.a,"Error creating offer: "+JSON.stringify(b))},this.P1);this.aM.promise.then(function(b){a.aK(b)})};d.MM=function(a){var b=this;G(this.a,"Setting local description: "+JSON.stringify(a));this.o.setLocalDescription(a,function(){G(b.a,"Local description set successfully")},function(a){F(b.a,"Error setting local description: "+JSON.stringify(a))})};
d.kV=function(a){return{type:a.type,sdp:a.sdp}};d.setRemoteDescription=function(a){var b=this;H(this.a,"<===: "+JSON.stringify(a));a=new RTCSessionDescription(a);G(this.a,"Setting remote description: "+JSON.stringify(a));this.o.setRemoteDescription(a,function(){G(b.a,"Remote description set successfully.")},function(a){F(b.a,"Error setting remote description: "+JSON.stringify(a))})};
d.lz=function(a){var b=this;a.candidate?(this.dt++,this.II=v(),1==this.dt?this.ss=ff(function(){G(b.a,"ICE candidate gathering timed out.");b.ss=null;b.vA()},5E3):this.GA&&F(this.a,"Received ICE candidate after resolving session description.")):(G(this.a,"End of ICE candidates."),zg("MediaRouter.WebRtc.IceCandidateGathering.Duration.Reported",v()-this.gz),this.vA(),0<this.dt&&zg("MediaRouter.WebRtc.IceCandidateGathering.Duration.Real",this.II-this.gz))};
d.Z2=function(){"completed"==this.o.iceGatheringState&&this.vA()};d.vA=function(){gf(this.ss);this.ss=null;this.GA||(G(this.a,"Resolving sesion description after gathering "+this.dt+" ICE candidates."),this.aM.resolve(this.kV(this.o.localDescription)),this.GA=!0)};
d.Y2=function(a){var b=this;if(this.o){var c=this.o.iceConnectionState;G(this.a,"New ICE connection state: "+c+".");"connected"==c?this.jz("iceconnected"):"completed"==c?this.jz("icecompleted"):"failed"==c?(F(this.a,"Ice connection failed: "+JSON.stringify(a)),this.SJ("icefailed")):"closed"==c?this.RJ("iceclosed"):"disconnected"==c&&(F(this.a,"Ice connection state is bad."),this.uU&&this.Bs()?(G(this.a,"Restarting ICE."),this.o.createOffer(u(this.MM,this),function(a){F(b.a,"Error creating new offer: "+
JSON.stringify(a))},ch)):this.E2())}};var ah={mandatory:{OfferToReceiveAudio:!0,OfferToReceiveVideo:!0}},ch={mandatory:{IceRestart:!0,OfferToReceiveAudio:!0,OfferToReceiveVideo:!0}};var dh=function(a){this.g8=a};dh.prototype.Fl=function(){return Promise.resolve(this.g8)};var eh=function(a,b){this.width=a;this.height=b};d=eh.prototype;d.clone=function(){return new eh(this.width,this.height)};d.toString=function(){return"("+this.width+" x "+this.height+")"};d.AR=function(){return this.width*this.height};d.$b=function(){return!this.AR()};d.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};d.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
d.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};d.scale=function(a,b){b=t(b)?b:a;this.width*=a;this.height*=b;return this};var fh=!Vc&&!Tc||Tc&&9<=Number(pd)||Vc&&od("1.9.1");Tc&&od("9");var hh=function(a,b){Ab(b,function(b,e){"style"==e?a.style.cssText=b:"class"==e?a.className=b:"for"==e?a.htmlFor=b:gh.hasOwnProperty(e)?a.setAttribute(gh[e],b):Ea(e,"aria-")||Ea(e,"data-")?a.setAttribute(e,b):a[e]=b})},gh={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},jh=function(a,b,c,e){function f(c){c&&b.appendChild(r(c)?
a.createTextNode(c):c)}for(;e<c.length;e++){var g=c[e];!va(g)||xa(g)&&0<g.nodeType?f(g):x(ih(g)?z(g):g,f)}},kh=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null},lh=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(String(b)))}},
ih=function(a){if(a&&"number"==typeof a.length){if(xa(a))return"function"==typeof a.item||"string"==typeof a.item;if(wa(a))return"function"==typeof a.item}return!1},mh=function(a){this.Bn=a||h.document||document};d=mh.prototype;d.getElementsByTagName=function(a,b){return(b||this.Bn).getElementsByTagName(String(a))};d.setProperties=hh;d.createElement=function(a){return this.Bn.createElement(String(a))};d.createTextNode=function(a){return this.Bn.createTextNode(String(a))};
d.getWindow=function(){var a=this.Bn;return a.parentWindow||a.defaultView};d.appendChild=function(a,b){a.appendChild(b)};d.append=function(a,b){jh(9==a.nodeType?a:a.ownerDocument||a.document,a,arguments,1)};d.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
d.removeNode=kh;d.getChildren=function(a){return fh&&void 0!=a.children?a.children:cb(a.childNodes,function(a){return 1==a.nodeType})};d.isElement=function(a){return xa(a)&&1==a.nodeType};d.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var nh=function(a,b){this.Ut=[];this.PJ=a;this.wE=b||null;this.lo=this.oc=!1;this.yd=void 0;this.tB=this.HR=this.Lv=!1;this.Nu=0;this.Ob=null;this.Mq=0};d=nh.prototype;d.cancel=function(a){if(this.oc)this.yd instanceof nh&&this.yd.cancel();else{if(this.Ob){var b=this.Ob;delete this.Ob;a?b.cancel(a):b.JR()}this.PJ?this.PJ.call(this.wE,this):this.tB=!0;this.oc||this.Ka(new oh(this))}};d.JR=function(){this.Mq--;0>=this.Mq&&this.cancel()};d.jE=function(a,b){this.Lv=!1;this.WB(a,b)};
d.WB=function(a,b){this.oc=!0;this.yd=b;this.lo=!a;this.rF()};d.LD=function(){if(this.oc){if(!this.tB)throw new ph(this);this.tB=!1}};d.callback=function(a){this.LD();this.WB(!0,a)};d.Ka=function(a){this.LD();this.WB(!1,a)};d.qa=function(a,b){return this.ii(a,null,b)};d.vc=function(a,b){return this.ii(null,a,b)};d.YQ=function(a,b){return this.ii(a,a,b)};d.ii=function(a,b,c){this.Ut.push([a,b,c]);this.oc&&this.rF();return this};
d.then=function(a,b,c){var e,f,g=new Qe(function(a,b){e=a;f=b});this.ii(e,function(a){a instanceof oh?g.cancel():f(a)});return g.then(a,b,c)};Ne(nh);d=nh.prototype;d.cw=function(a){this.ii(a.callback,a.Ka,a);return this};d.nD=function(a){return a instanceof nh?this.qa(u(a.Ov,a)):this.qa(function(){return a})};d.Ov=function(a){var b=new nh;this.cw(b);a&&(b.Ob=this,this.Mq++);return b};d.J0=function(a){return a instanceof Error};d.XH=function(){return db(this.Ut,function(a){return wa(a[1])})};
d.rF=function(){if(this.Nu&&this.oc&&this.XH()){var a=this.Nu,b=qh[a];b&&(b.b7(),delete qh[a]);this.Nu=0}this.Ob&&(this.Ob.Mq--,delete this.Ob);for(var a=this.yd,c=b=!1;this.Ut.length&&!this.Lv;){var e=this.Ut.shift(),f=e[0],g=e[1],e=e[2];if(f=this.lo?g:f)try{var k=f.call(e||this.wE,a);l(k)&&(this.lo=this.lo&&(k==a||this.J0(k)),this.yd=a=k);if(Oe(a)||"function"===typeof h.Promise&&a instanceof h.Promise)this.Lv=c=!0}catch(p){a=p,this.lo=!0,this.XH()||(b=!0)}}this.yd=a;c&&(k=u(this.jE,this,!0),c=u(this.jE,
this,!1),a instanceof nh?(a.ii(k,c),a.HR=!0):a.then(k,c));b&&(a=new rh(a),qh[a.Yb]=a,this.Nu=a.Yb)};var sh=function(a){var b=new nh;b.callback(a);return b},th=function(a){var b=new nh;b.Ka(a);return b},ph=function(){Da.call(this)};w(ph,Da);ph.prototype.message="Deferred has already fired";ph.prototype.name="AlreadyCalledError";var oh=function(){Da.call(this)};w(oh,Da);oh.prototype.message="Deferred was canceled";oh.prototype.name="CanceledError";
var rh=function(a){this.Yb=h.setTimeout(u(this.Dca,this),0);this.rd=a};rh.prototype.Dca=function(){delete qh[this.Yb];throw this.rd;};rh.prototype.b7=function(){h.clearTimeout(this.Yb)};var qh={};var yh=function(a,b){var c=b||{};b=c.document||document;var e=jc(a),f=document.createElement("SCRIPT");a={NL:f,Tp:void 0};var g=new nh(uh,a),k=null,p=null!=c.timeout?c.timeout:5E3;0<p&&(k=window.setTimeout(function(){vh(f,!0);g.Ka(new wh(1,"Timeout reached for loading script "+e))},p),a.Tp=k);f.onload=f.onreadystatechange=function(){f.readyState&&"loaded"!=f.readyState&&"complete"!=f.readyState||(vh(f,c.Lja||!1,k),g.callback(null))};f.onerror=function(){vh(f,!0,k);g.Ka(new wh(0,"Error while loading script "+
e))};a=c.attributes||{};Nb(a,{type:"text/javascript",charset:"UTF-8",src:e});hh(f,a);xh(b).appendChild(f);return g},xh=function(a){var b=(a||document).getElementsByTagName("HEAD");return b&&0!=b.length?b[0]:a.documentElement},uh=function(){if(this&&this.NL){var a=this.NL;a&&"SCRIPT"==a.tagName&&vh(a,!0,this.Tp)}},vh=function(a,b,c){null!=c&&h.clearTimeout(c);a.onload=pa;a.onerror=pa;a.onreadystatechange=pa;b&&window.setTimeout(function(){kh(a)},0)},wh=function(a,b){var c="Jsloader error (code #"+
a+")";b&&(c+=": "+b);Da.call(this,c);this.code=a};w(wh,Da);var zh=function(){this.Zb=this.kj=this.ps=null;this.Py=new Vd};d=zh.prototype;d.Fl=function(){var a=this;if(this.ps)return Promise.resolve(this.ps);this.u1().then(null,function(){a.Py.reject(Error("Failed to load hangouts mirroring script."))});return this.Py.promise};d.O9=function(a){this.Zb=a};d.s$=function(a){this.kj=a};d.fL=function(a){this.kj&&(this.ps=a(this.Zb,this.kj),this.Py.resolve(this.ps))};d.u1=function(){var a=chrome.extension.getURL("mirroring_hangouts.js"),a=kc(a);return yh(a,void 0)};
ra(zh);var Ah="undefined"!=typeof chrome&&!!chrome.networkingPrivate&&!!chrome.networkingPrivate.setWifiTDLSEnabledState&&Kg(),Bh=Kg()||ad;var Dh=function(){this.maxWidth=1920;this.maxHeight=1080;this.minWidth=320;this.minHeight=180;this.maxFrameRate=30;this.minVideoBitrate=300;this.maxVideoBitrate=5E3;this.audioBitrate=128;this.maxLatencyMillis=800;this.animatedLatencyMillis=this.minLatencyMillis=400;this.dscpEnabled=$c||bd||Kg()||Lg();this.enableLogging=!0;this.useTdls=!1;this.captureAudio=this.captureVideo=!0;this.a=D("mr.mirror.Settings");var a=window.localStorage?window.localStorage.getItem(Ch):null;if(r(a))try{var b=JSON.parse(a);
b&&(this.TO(b),F(this.a,"Initial mr.mirror.Settings overridden to: "+this.IB()))}catch(c){throw E(this.a,Ch+' must be of the form \'{"maxWidth":640, "maxHeight":360}\'.',c),Error("Overrides not parseable.  See ERROR log for details.");}},Ch="mr.mirror.Settings.Overrides";d=Dh.prototype;d.clone=function(){var a=new Dh;a.TO(this);return a};d.IB=function(){return JSON.stringify(this,function(a,b){if(0==a.length||"boolean"==typeof b||"number"==typeof b||"string"==typeof b)return b})};
d.TO=function(a){for(var b in this){var c=a[b];if(null!=c){var e=this[b];"boolean"!=typeof e&&"number"!=typeof e&&"string"!=typeof e||typeof e!=typeof c||(this[b]=c)}}};
d.SS=function(){var a=screen.width,b=screen.height;this.maxHeight*a<this.maxWidth*b?(a=Math.min(this.maxWidth,a),a-=a%160,b=90*a/160):(b=Math.min(this.maxHeight,b),b-=b%90,a=160*b/90);if(a<Math.max(160,this.minWidth)||b<Math.max(90,this.minHeight))a=Math.max(160,this.minWidth),b=Math.max(90,this.minHeight);this.maxWidth=a;this.maxHeight=b};d.ZT=function(){this.minHeight=this.minWidth=0};
var Eh=function(a,b){var c=new Dh;c.captureAudio=a;c.captureVideo=b;c.SS();G(c.a,"mr.mirror.Settings after screen size adjustments: "+c.IB());return c};Dh.prototype.eY=function(){return String(this.minWidth+"x"+this.minHeight)};Dh.prototype.QX=function(){return String(this.maxWidth+"x"+this.maxHeight)};Dh.prototype.bZ=function(){return this.minWidth==this.maxWidth&&this.minHeight==this.maxHeight?"fixed":0<this.minWidth&&0<this.minHeight?"fixed-aspect-ratio":"variable"};var Fh=function(a,b,c,e){this.ED=a;this.Mb=b;this.k2=c||null;this.r5=e||null};d=Fh.prototype;d.zI=function(){return"tab"==this.ED};d.wI=function(){return"offscreen_tab"==this.ED};d.JB=function(a){return this.zI()?this.uO():this.wI()?this.Jca():this.Hca(a)};
d.uO=function(){var a={audio:this.Mb.captureAudio,video:this.Mb.captureVideo};this.Mb.captureVideo&&(a.videoConstraints={mandatory:{minWidth:this.Mb.minWidth,minHeight:this.Mb.minHeight,maxWidth:this.Mb.maxWidth,maxHeight:this.Mb.maxHeight,maxFrameRate:this.Mb.maxFrameRate,enableAutoThrottling:!0}});return a};d.Jca=function(){var a=this.uO();a.presentationId=this.r5;return a};
d.Hca=function(a){var b={audio:!1,video:!1};this.Mb.captureVideo&&(b.video={mandatory:{chromeMediaSource:"desktop",chromeMediaSourceId:a,minWidth:this.Mb.minWidth,minHeight:this.Mb.minHeight,maxWidth:this.Mb.maxWidth,maxHeight:this.Mb.maxHeight,maxFrameRate:this.Mb.maxFrameRate}});Bh&&this.Mb.captureAudio&&(b.audio={mandatory:{chromeMediaSource:"desktop",chromeMediaSourceId:a}});return b};var Gh=function(a,b,c){Pg(a)||Qg(a);this.Wy=a;this.Mb=b;this.f4=c||null};Gh.prototype.fg=function(){return this.Mb};Gh.prototype.gx=function(){return this.ry()?new Fh("tab",this.Mb):this.xI()?new Fh("offscreen_tab",this.Mb,this.Wy,this.f4.toString()):new Fh("desktop",this.Mb)};Gh.prototype.ry=function(){return Og(this.Wy)};Gh.prototype.xI=function(){return Qg(this.Wy)};var Hh=A("Firefox"),Ih=Oc()||A("iPod"),Jh=A("iPad"),Kh=A("Android")&&!(Yb()||A("Firefox")||A("Opera")||A("Silk")),Lh=Yb(),Mh=A("Safari")&&!(Yb()||A("Coast")||A("Opera")||A("Edge")||A("Silk")||A("Android"))&&!(Oc()||A("iPad")||A("iPod"));var Nh=function(a){return y(a,function(a){a=a.toString(16);return 1<a.length?a:"0"+a}).join("")};var Oh=null,Ph=null,Qh=null,Rh=Vc||Wc&&!Mh||Sc||!Mh&&!Tc&&"function"==typeof h.atob,Th=function(a,b){Sh();b=b?Qh:Oh;for(var c=[],e=0;e<a.length;e+=3){var f=a[e],g=e+1<a.length,k=g?a[e+1]:0,p=e+2<a.length,q=p?a[e+2]:0,B=f>>2,f=(f&3)<<4|k>>4,k=(k&15)<<2|q>>6,q=q&63;p||(q=64,g||(k=64));c.push(b[B],b[f],b[k],b[q])}return c.join("")},Vh=function(a,b){if(Rh&&!b)return h.atob(a);var c="";Uh(a,function(a){c+=String.fromCharCode(a)});return c},Wh=function(a){var b=new Uint8Array(Math.ceil(3*a.length/4)),c=
0;Uh(a,function(a){b[c++]=a});return b.subarray(0,c)},Uh=function(a,b){function c(b){for(;e<a.length;){var c=a.charAt(e++),f=Ph[c];if(null!=f)return f;if(!Ga(c))throw Error("Unknown base64 encoding at char: "+c);}return b}Sh();for(var e=0;;){var f=c(-1),g=c(0),k=c(64),p=c(64);if(64===p&&-1===f)break;b(f<<2|g>>4);64!=k&&(b(g<<4&240|k>>2),64!=p&&b(k<<6&192|p))}},Sh=function(){if(!Oh){Oh={};Ph={};Qh={};for(var a=0;65>a;a++)Oh[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a),
Ph[Oh[a]]=a,Qh[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a),62<=a&&(Ph["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a)]=a)}};var Xh=function(a){I.call(this);this.C=a;this.Ga={}};w(Xh,I);var Yh=[];d=Xh.prototype;d.listen=function(a,b,c,e){return this.YI(a,b,c,e)};d.p1=function(a,b,c,e,f){return this.YI(a,b,c,e,f)};d.YI=function(a,b,c,e,f){ua(b)||(b&&(Yh[0]=b.toString()),b=Yh);for(var g=0;g<b.length;g++){var k=me(a,b[g],c||this.handleEvent,e||!1,f||this.C||this);if(!k)break;this.Ga[k.key]=k}return this};d.Bo=function(a,b,c,e){return this.WI(a,b,c,e)};
d.WI=function(a,b,c,e,f){if(ua(b))for(var g=0;g<b.length;g++)this.WI(a,b[g],c,e,f);else{a=te(a,b,c||this.handleEvent,e,f||this.C||this);if(!a)return this;this.Ga[a.key]=a}return this};d.jd=function(a,b,c,e,f){if(ua(b))for(var g=0;g<b.length;g++)this.jd(a,b[g],c,e,f);else c=c||this.handleEvent,f=f||this.C||this,c=ne(c),e=!!e,b=ee(a)?a.Tn(b,c,e,f):a?(a=pe(a))?a.Tn(b,c,e,f):null:null,b&&(ve(b),delete this.Ga[b.key]);return this};
d.removeAll=function(){Ab(this.Ga,function(a,b){this.Ga.hasOwnProperty(b)&&ve(a)},this);this.Ga={}};d.L=function(){Xh.U.L.call(this);this.removeAll()};d.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Zh=function(a){this.Rl=0;this.Jl=a||100;this.Mf=[]};d=Zh.prototype;d.add=function(a){var b=this.Mf[this.Rl];this.Mf[this.Rl]=a;this.Rl=(this.Rl+1)%this.Jl;return b};d.get=function(a){a=this.IJ(a);return this.Mf[a]};d.set=function(a,b){a=this.IJ(a);this.Mf[a]=b};d.S=function(){return this.Mf.length};d.$b=function(){return 0==this.Mf.length};d.clear=function(){this.Rl=this.Mf.length=0};d.F=function(){return this.pY(this.S())};
d.pY=function(a){var b=this.S(),c=[];for(a=this.S()-a;a<b;a++)c.push(this.get(a));return c};d.kb=function(){for(var a=[],b=this.S(),c=0;c<b;c++)a[c]=c;return a};d.ya=function(a){return a<this.S()};d.Ek=function(a){for(var b=this.S(),c=0;c<b;c++)if(this.get(c)==a)return!0;return!1};d.IJ=function(a){if(a>=this.Mf.length)throw Error("Out of bounds exception");return this.Mf.length<this.Jl?a:(this.Rl+Number(a))%this.Jl};var $h=function(){this.iL=v()},ai=new $h;$h.prototype.set=function(a){this.iL=a};$h.prototype.reset=function(){this.set(v())};$h.prototype.get=function(){return this.iL};var bi=function(a){this.p5=a||"";this.gca=ai};d=bi.prototype;d.aD=!0;d.rB=!0;d.Fba=!0;d.Eba=!0;d.ou=!1;d.sB=!1;d.Zw=n;
var di=function(a){a=new Date(a.pO);return ci(a.getFullYear()-2E3)+ci(a.getMonth()+1)+ci(a.getDate())+" "+ci(a.getHours())+":"+ci(a.getMinutes())+":"+ci(a.getSeconds())+"."+ci(Math.floor(a.getMilliseconds()/10))},ci=function(a){return 10>a?"0"+a:String(a)},ei=function(a,b){a=(a.pO-b)/1E3;b=a.toFixed(3);var c=0;if(1>a)c=2;else for(;100>a;)c++,a*=10;for(;0<c--;)b=" "+b;return b},fi=function(a){bi.call(this,a)};w(fi,bi);
fi.prototype.Zw=function(a){var b=[];b.push(this.p5," ");this.rB&&b.push("[",di(a),"] ");this.Fba&&b.push("[",ei(a,this.gca.get()),"s] ");this.Eba&&b.push("[",a.bJ,"] ");this.sB&&b.push("[",a.Bh.name,"] ");b.push(a.getMessage());this.ou&&(a=a.tr)&&b.push("\n",a instanceof Error?a.message:a.toString());this.aD&&b.push("\n");return b.join("")};var gi=function(a){return(a=a.exec(Vb))?a[1]:""},hi=function(){if(Hh)return gi(/Firefox\/([0-9.]+)/);if(Tc||Uc||Sc)return ld;if(Lh)return gi(/Chrome\/([0-9.]+)/);if(Mh&&!(Oc()||A("iPad")||A("iPod")))return gi(/Version\/([0-9.]+)/);if(Ih||Jh){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Vb);if(a)return a[1]+"."+a[2]}else if(Kh)return(a=gi(/Android\s+([0-9.]+)/))?a:gi(/Version\/([0-9.]+)/);return""}();var ii=function(){this.wc=-1};ii.prototype.reset=n;ii.prototype.update=n;ii.prototype.digest=n;var ji=function(){this.wc=64;this.fa=[];this.Qv=[];this.RQ=[];this.lt=[];this.lt[0]=128;for(var a=1;a<this.wc;++a)this.lt[a]=0;this.Ku=this.wl=0;this.reset()};w(ji,ii);ji.prototype.reset=function(){this.fa[0]=1732584193;this.fa[1]=4023233417;this.fa[2]=2562383102;this.fa[3]=271733878;this.fa[4]=3285377520;this.Ku=this.wl=0};
ji.prototype.$g=function(a,b){b||(b=0);var c=this.RQ;if(r(a))for(var e=0;16>e;e++)c[e]=a.charCodeAt(b)<<24|a.charCodeAt(b+1)<<16|a.charCodeAt(b+2)<<8|a.charCodeAt(b+3),b+=4;else for(e=0;16>e;e++)c[e]=a[b]<<24|a[b+1]<<16|a[b+2]<<8|a[b+3],b+=4;for(e=16;80>e;e++){var f=c[e-3]^c[e-8]^c[e-14]^c[e-16];c[e]=(f<<1|f>>>31)&4294967295}a=this.fa[0];b=this.fa[1];for(var g=this.fa[2],k=this.fa[3],p=this.fa[4],q,e=0;80>e;e++)40>e?20>e?(f=k^b&(g^k),q=1518500249):(f=b^g^k,q=1859775393):60>e?(f=b&g|k&(b|g),q=2400959708):
(f=b^g^k,q=3395469782),f=(a<<5|a>>>27)+f+p+q+c[e]&4294967295,p=k,k=g,g=(b<<30|b>>>2)&4294967295,b=a,a=f;this.fa[0]=this.fa[0]+a&4294967295;this.fa[1]=this.fa[1]+b&4294967295;this.fa[2]=this.fa[2]+g&4294967295;this.fa[3]=this.fa[3]+k&4294967295;this.fa[4]=this.fa[4]+p&4294967295};
ji.prototype.update=function(a,b){if(null!=a){l(b)||(b=a.length);for(var c=b-this.wc,e=0,f=this.Qv,g=this.wl;e<b;){if(0==g)for(;e<=c;)this.$g(a,e),e+=this.wc;if(r(a))for(;e<b;){if(f[g]=a.charCodeAt(e),++g,++e,g==this.wc){this.$g(f);g=0;break}}else for(;e<b;)if(f[g]=a[e],++g,++e,g==this.wc){this.$g(f);g=0;break}}this.wl=g;this.Ku+=b}};
ji.prototype.digest=function(){var a=[],b=8*this.Ku;56>this.wl?this.update(this.lt,56-this.wl):this.update(this.lt,this.wc-(this.wl-56));for(var c=this.wc-1;56<=c;c--)this.Qv[c]=b&255,b/=256;this.$g(this.Qv);for(c=b=0;5>c;c++)for(var e=24;0<=e;e-=8)a[b]=this.fa[c]>>e&255,++b;return a};var ki=function(a,b,c,e,f,g,k,p){this.Od=null;this.TD=!1;this.SD=$e();this.Dc=[];this.Jf=a?encodeURIComponent(String(a)):null;this.xF=null;!e&&b&&(this.xF=b);this.wR=c||null;this.Fq=!e;this.or=null!=f?f:null;this.et=g||null;this.vda=!!k;this.yF=p||null};w(ki,I);var li;var mi=ac("https://apis.google.com/js/client.js");mi instanceof $b&&mi.constructor===$b&&mi.yQ===Zb?li=mi.CB:(Ya("expected object of type Const, got '"+mi+"'"),li="type_error:Const");var ni=kc(li);d=ki.prototype;
d.init=function(){var a=u(function(a){this.Od=a;var b=oa("client.request",a),c=oa("auth",a);b&&c?this.NH():a.load("client",u(this.NH,this))},this),b=this.lF("gapi");b?a(b.gapi):this.t1(a);return this.SD.promise};d.lF=function(a){for(var b=window,c=oa(a,b);!c&&b!=window.top&&this.uS(b.parent,a);)b=b.parent,c=oa(a,b);return c?b:null};d.uS=function(a,b){try{return!!a&&null!=a.location.href&&Qc(a,b)}catch(c){return!1}};
d.t1=function(a){var b=this.lF("gapi_onload");if(b){var c=b.gapi_onload;b.gapi_onload=function(){c();a(b.gapi)}}else{window.gapi_onload=function(){a(window.gapi)};var e=document.createElement("script");e.src=jc(ni);this.yF&&lh(e,nf(this.yF));document.getElementsByTagName("head")[0].appendChild(e)}};d.NH=function(){for(var a=0;a<this.Dc.length;a++)this.Dc[a].Cb.resolve(this.YL(this.Dc[a].S6));this.TD=!0;this.SD.resolve(this.Od)};
d.sendRequest=function(a){if(this.TD)return this.YL(a);var b=$e();this.Dc.push({S6:a,Cb:b});return b.promise};
d.YL=function(a){var b,c,e,f=oa("config.get",this.Od);this.Fq||(b=f("googleapis.config/auth/useFirstPartyAuth"),c=f("googleapis.config/auth/useOriginToken"));null!=this.or&&(e=f("client/cors"));try{var g=oa("config.update",this.Od);this.Fq||(g("googleapis.config/auth/useFirstPartyAuth",!1),g("googleapis.config/auth/useOriginToken",!1));null!=this.or&&g("client/cors",this.or);var k=oa("client.request",this.Od),p=this.CV();a.headers&&Nb(p,a.headers);var q={headers:p,root:this.wR,path:a.path,method:a.method,
body:a.body},B=a.params||{};this.Jf&&!this.et?Nb(B,{key:this.Jf}):this.et&&Nb(B,{key:null});Hb(B)||(q.params=B);var O=Ue(k(q));a.callback&&O.then(function(b){a.callback.apply(null,[b.result,b])},function(b){a.callback.apply(null,[b.result,b])});return O}finally{g=oa("config.update",this.Od),this.Fq||(g("googleapis.config/auth/useFirstPartyAuth",b),g("googleapis.config/auth/useOriginToken",c)),null!=this.or&&g("client/cors",e)}};
d.CV=function(){if(this.Fq){if(this.et)return{Authorization:"Bearer "+this.et};var a=oa("auth.getAuthHeaderValueForFirstParty",this.Od);return{Authorization:this.vda?a([]):a(),"X-Goog-AuthUser":this.xF}}return{}};
